### ISSUE TITLE
Dashboard graphs missing

### ISSUE THREAD

**Issue by pedroresende** [datreks/codetime-vscode#15]
![image](https://user-images.githubusercontent.com/951377/150174110-84aee586-e1d3-4aa1-8e85-162a79445de4.png)

**Comment by si9ma** [comment]
@Jannchie

**Comment by pedroresende** [comment]
Seems the dashboard isn't loading anymore, don't know if the extension is still alive

**Comment by pedroresende** [comment]
![image](https://user-images.githubusercontent.com/951377/151795195-5d87521c-8b99-4a9f-96f8-a55f8146cfeb.png)

**Comment by si9ma** [comment]
@pedroresende It's fixed now. I'm very sorry, it's Chinese New Year recently, so I didn't have time to deal with this issue. codetime currently has some stability and experience issues. We will refactor and optimize the whole after the Chinese New Year. Happy New Year!

**Comment by pedroresende** [comment]
Thanks for the hard work @si9ma. It's a great app, please let me know if I can help somehow

**Comment by pedroresende** [comment]
![image](https://user-images.githubusercontent.com/951377/153750241-bf4e34b1-d7d1-4942-8558-37a85eefc74a.png)

![image](https://user-images.githubusercontent.com/951377/153750246-895ec445-bd74-45f5-b92c-1eaa37b781bd.png)

The issue is still present

**Comment by Jannchie** [comment]
@pedroresende  I can't reproduce the problem on my end, but I'm working on it. Thank you for your feedback.

**Comment by Jannchie** [comment]
Thank you for your support and for bringing this issue to our attention. We are pleased to inform you that we have rewritten the code and the dashboard is now accessible at codetime.dev. We understand that we may not have met your expectations in the past, but moving forward, we will make every effort to ensure the stability of our service.
